# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daimon < Formula
  desc "The spirit that runs alongside your AI app — a pluggable sidecar runtime for LLMs"
  homepage "https://github.com/sonicboom15/daimon"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sonicboom15/daimon/releases/download/v0.0.2/daimon_0.0.2_darwin_amd64.tar.gz"
      sha256 "5d8266ffaa580305cb314c90f45f8dc870fe8fe6aea10beac7cea957cc9f0388"

      define_method(:install) do
        bin.install "daimon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sonicboom15/daimon/releases/download/v0.0.2/daimon_0.0.2_darwin_arm64.tar.gz"
      sha256 "8fecb5760496bc4aec4a3d503dc1f6723f46e3d7a3a9fbcb40fa2b2a261546bb"

      define_method(:install) do
        bin.install "daimon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonicboom15/daimon/releases/download/v0.0.2/daimon_0.0.2_linux_amd64.tar.gz"
      sha256 "bb2c7bd728f821339eb1669aed4f051b1be4673111d0bddf24a4ff6ed0085581"
      define_method(:install) do
        bin.install "daimon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonicboom15/daimon/releases/download/v0.0.2/daimon_0.0.2_linux_arm64.tar.gz"
      sha256 "fa9fb7262c4dd8eb3e4151068df842ba31f97327491369f8cd1ea1acaceeccc3"
      define_method(:install) do
        bin.install "daimon"
      end
    end
  end

  test do
    system "#{bin}/daimon", "--help"
  end
end
