# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daimon < Formula
  desc "The spirit that runs alongside your AI app — a pluggable sidecar runtime for LLMs"
  homepage "https://github.com/sonicboom15/daimon"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sonicboom15/daimon/releases/download/v0.0.3/daimon_0.0.3_darwin_amd64.tar.gz"
      sha256 "2eed2b0e467f1fd92a6d54fed42b8a4640f40c4ff7bc109b4896658e1dae3aa8"

      define_method(:install) do
        bin.install "daimon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sonicboom15/daimon/releases/download/v0.0.3/daimon_0.0.3_darwin_arm64.tar.gz"
      sha256 "5fb4a1bf06aeac46d1b6d53ab2c1c9a50c789db2288f586087317e542b47b717"

      define_method(:install) do
        bin.install "daimon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonicboom15/daimon/releases/download/v0.0.3/daimon_0.0.3_linux_amd64.tar.gz"
      sha256 "bd11db0cb0da90667e35578bcf669408ea54c514894b364a8672e30d3ac8697e"
      define_method(:install) do
        bin.install "daimon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonicboom15/daimon/releases/download/v0.0.3/daimon_0.0.3_linux_arm64.tar.gz"
      sha256 "11faf5bb03b08b6e099515b6b7a6a0077d31e1326493df1463bb650f8ee8ef81"
      define_method(:install) do
        bin.install "daimon"
      end
    end
  end

  test do
    system "#{bin}/daimon", "--help"
  end
end
