# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daimon < Formula
  desc "The spirit that runs alongside your AI app — a pluggable sidecar runtime for LLMs"
  homepage "https://github.com/sonicboom15/daimon"
  version "0.2.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sonicboom15/daimon/releases/download/v0.2.6/daimon_0.2.6_darwin_amd64.tar.gz"
      sha256 "f7002ba96447d48aa122f11a77345b73bfe04a36af92d3792bf932a1bf77f88c"

      define_method(:install) do
        bin.install "daimon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sonicboom15/daimon/releases/download/v0.2.6/daimon_0.2.6_darwin_arm64.tar.gz"
      sha256 "483b9fcdd711c8c06a2f256ee48ae6235e4f7e27c239e892fcac2c44e61cece3"

      define_method(:install) do
        bin.install "daimon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonicboom15/daimon/releases/download/v0.2.6/daimon_0.2.6_linux_amd64.tar.gz"
      sha256 "e96e5ca747a910888e7e8696b8bca680ef67295d4324f033d06c3ea965294f8a"
      define_method(:install) do
        bin.install "daimon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonicboom15/daimon/releases/download/v0.2.6/daimon_0.2.6_linux_arm64.tar.gz"
      sha256 "b8a1d8f6af043b18980937025bf487f2f22c8d67e52f4d1291bec816d701dd52"
      define_method(:install) do
        bin.install "daimon"
      end
    end
  end

  test do
    system "#{bin}/daimon", "--help"
  end
end
